In [1]:
import numpy as np
import pandas as pd
import itertools
import string
from sympy import sympify

In [2]:
class LogicTable():
    def __init__(self, n:int):
        self.columns = list(string.ascii_uppercase)[:n]
        self.bools = [True, False]
        self.df = pd.DataFrame(list(itertools.product(self.bools, repeat=n)), columns=self.columns)
        
    @property
    def df_01(self):
        return self.df.astype(int)

    def add(self, prop):
        prop = str(sympify(prop))
        self.df[prop] = self.df.eval(prop)
        return self

    def re_add(self, prop):
        prop = sympify(prop)
        if not prop.args:
            return
        
        for arg in prop.args:
            self.re_add(arg)
        
        col_name = str(prop)
        
        if col_name not in self.df.columns:
            self.df[col_name] = self.df.eval(col_name)

In [3]:
text = "(A | B) & (A | C)"

logic = LogicTable(n=3)

logic.re_add(prop=text)
logic.df_01

   A  B  C  A | B  A | C  (A | B) & (A | C)
0  1  1  1      1      1                  1
1  1  1  0      1      1                  1
2  1  0  1      1      1                  1
3  1  0  0      1      1                  1
4  0  1  1      1      1                  1
5  0  1  0      1      0                  0
6  0  0  1      0      1                  0
7  0  0  0      0      0                  0

In [4]:
text = "A | (B & C)"

logic = LogicTable(n=3)

logic.re_add(prop=text)
logic.df_01

   A  B  C  B & C  A | (B & C)
0  1  1  1      1            1
1  1  1  0      0            1
2  1  0  1      0            1
3  1  0  0      0            1
4  0  1  1      1            1
5  0  1  0      0            0
6  0  0  1      0            0
7  0  0  0      0            0